Document multiple calls with `allow_any_instance_of`
rspec/rspec-mocks pull request #1510
Opened 2022-12-29 22:43 UTC by nycdotnet

Hello,

I have attempted to improve the documentation for the multiple calls feature in combination with everyone's friend `allow_any_instance_of`.  It does have some confusing behavior as identified in the docs.  I hope that documenting the expected behavior here should at least mitigate confusion when used in combination with multiple call mocks.

Please let me know if you have any questions.  I hope this PR is acceptable without having opened an issue first.  I believe that this file corresponds with this document: https://relishapp.com/rspec/rspec-mocks/docs/configuring-responses/returning-a-value#specify-different-return-values-for-multiple-calls

Thank you.

2023-01-07 10:13 UTC, JonRowe requested changes
Hi, can you move the extra scenario to `features/working_with_legacy_code/any_instance.feature` thats where they live as we try to semi discourage usage of it (its a huge maintenance burden for us and its considered best for legacy tests).

2023-01-07 14:03 UTC, nycdotnet commented
Sure.  Is it ok if I link to it from here?  Something like “See here for considerations when working with legacy code”.  Thanks.

2023-01-07 20:40 UTC, JonRowe commented
Its already linked to elsewhere? Do you find it difficult to find the page?

2023-01-24 15:57 UTC, nycdotnet commented
Well since this example didn't exist, I do think it was difficult to find! :-)

I fully understand and respect the desire to keep this functionality compartmentalized since it's specifically for legacy that isn't easy to test otherwise.  I think that's a worthy goal because it encourages people to write things in a better way.

My thought here is that this behavior feels more contextually specific to the behavior of `and_return`, so at least having a link to the legacy feature page with another discouragement would help to clarify how it's intended to work but would reinforce the "you should try to restructure your code if possible to make this not necessary" aka "don't do this" message.  I'll put it together that way and see what you think.  It's ok to delete the cross reference if you think it's not aligned with your goals.

Thank you!

2023-01-24 16:49 UTC, nycdotnet commented
I am investigating the build failures.

2023-01-24 17:05 UTC, nycdotnet commented
Running `script/run_build` passes locally now - sorry for the trouble.

I am curious if you have a thought on the links to `.feature` - should I remove that extension in the markdown or is it resolved in the generation?  The link on the real site would not have `.feature` on it.

Thank you.

2023-02-17 15:23 UTC, nycdotnet commented
@JonRowe sorry to trouble you, but is this PR now satisfactory?  Thank you.

2023-02-22 10:34 UTC, merged

2023-02-22 11:20 UTC, JonRowe commented
Thanks for the contribution, apologies it has taken so long, I'm doing some minor rewording and will then get this up on the docs.

2023-02-22 23:58 UTC, nycdotnet commented
@JonRowe excellent - many thanks for the review.